import{a as q,S as P,i as n}from"./assets/vendor-BNibzuFn.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const s of o.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&i(s)}).observe(document,{childList:!0,subtree:!0});function t(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=t(e);fetch(e.href,o)}})();const B="52351532-fc595975ad786aa616f582edd",E="https://pixabay.com/api/";async function p(r,a=1){const{data:t}=await q.get(E,{params:{key:B,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:a}});return t}const m=document.querySelector(".gallery"),f=document.querySelector(".loader"),g=document.querySelector(".load-more"),M=new P(".gallery a",{captionsData:"alt",captionDelay:250});function h(r){const a=r.map(({webformatURL:t,largeImageURL:i,tags:e,likes:o,views:s,comments:w,downloads:b})=>`
      <li class="gallery-item">
        <a href="${i}">
          <img src="${t}" alt="${e}" />
          <div class="info">
            <p><span class='label'>Likes:</span><span class='value'>${o}</span></p>
            <p><span class='label'>Views:</span><span class='value'>${s}</span></p>
            <p><span class='label'>Comments:</span><span class='value'>${w}</span></p>
            <p><span class='label'>Downloads:</span><span class='value'>${b}</span></p>
          </div>
        </a>
      </li>
    `).join("");m.insertAdjacentHTML("beforeend",a),M.refresh()}function $(){m.innerHTML=""}function y(){f.classList.add("active")}function l(){f.classList.remove("active")}function L(){g.classList.add("active")}function u(){g.classList.remove("active")}const v=document.querySelector(".form"),R=v.querySelector('input[name="search-text"]'),O=document.querySelector(".load-more");let d="",c=1,S=0;v.addEventListener("submit",x);O.addEventListener("click",A);async function x(r){r.preventDefault();const a=R.value.trim();if(!a){n.warning({title:"Warning",message:"Please enter a search term!",position:"topRight"});return}d=a,c=1,$(),u(),y();try{const t=await p(d,c);if(l(),S=t.totalHits,!t.hits||t.hits.length===0){n.error({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}h(t.hits),t.totalHits>t.hits.length&&L()}catch(t){l(),n.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"}),console.error(t)}}async function A(){c+=1,u(),y();try{const r=await p(d,c);l(),h(r.hits),H(),document.querySelectorAll(".gallery-item").length>=S?(u(),n.info({title:"End",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):L()}catch(r){l(),n.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"}),console.error(r)}}function H(){const{height:r}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
